export enum AuditAction {
  ContentUpload = 'content.upload',
  ContentDelete = 'content.delete',
  ContentReupload = 'content.reupload',
  PlaylistCreate = 'playlist.create',
  PlaylistUpdate = 'playlist.update',
  PlaylistDelete = 'playlist.delete',
  ScheduleCreate = 'schedule.create',
  ScheduleUpdate = 'schedule.update',
  ScheduleDelete = 'schedule.delete',
  ScreenRegister = 'screen.register',
  ScreenUpdate = 'screen.update',
  ScreenKeyRegenerated = 'screen.key_regenerated',
  ScreenOnline = 'screen.online',
  ScreenOffline = 'screen.offline',
  UserInvited = 'user.invited',
  UserRoleChanged = 'user.role_changed',
  UserRemoved = 'user.removed',
  OrganisationCreated = 'organisation.created',
  OrganisationUpdated = 'organisation.updated',
  GroupCreated = 'group.created',
  GroupUpdated = 'group.updated',
  GroupDeleted = 'group.deleted',
  GroupScreenAdded = 'group.screen_added',
  GroupScreenRemoved = 'group.screen_removed',
  GroupModeChanged = 'group.mode_changed',
}
