# Stage 1: Build
FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npx ng build --configuration production

# Stage 2: Production runtime
FROM nginx:alpine

COPY nginx.prod.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist/player/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
